#Carrega bibliotecas

install.packages("ggrepel")
install.packages("esquisse")
install.packages("zoo")
install.packages("ggplot2")
install.packages("tidyr")
install.packages("tibble")
install.packages("dplyr")
install.packages("lubridate")
install.packages("RColorBrewer")
install.packages("forcats")
install.packages("tidyverse")


library(ggplot2)
library(tidyr)
library(tibble)
library(dplyr)
library(lubridate)
library(plyr)
library(RColorBrewer)
library(ggrepel)
library(esquisse)
library(zoo)
library(forcats)
detach(package:plyr)
library(tidyverse)
